export * from "./bpmn/BmpnPalette";
export * from "./misc/MiscPalette";
export * from "./Palettes";
export * from "./uml/UmlPalette";
export * from "./basic/BasicPalette";
export * from "./stencil/StencilPalette";
export * from "./search/SearchPalette";
export * from "./image/ImagePalette";
export * from "./general/GeneralPalette";
